[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Materials"
identifier = "materials"
weight = 200
url = "/materials"

[[main]]
name = "Personal"
identifier = "personal"
weight = 300

[[main]]
name = "ToDo"
identifier = "todo"
weight = 310
url = "/todo"
parent = "personal"

[[main]]
name = "Rewind"
identifier = "rewind"
weight = 320
url = "/rewind"
parent = "personal"