
title = "tK's 451s"
author = "Kinsley Hsu"
copyright = "Kinsley Hsu 2023-2025"
description = "Happiness is a prerequisite for life, so just leave those who damages it."

profilePicture = "/img/profile.jpg"
keywords = ""
favicon = "/img/"

# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["/img/favicon.ico"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3


reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"
# trackerScriptName = "mycustomscriptname.js"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[socialIcons]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/theKinsley"

[[socialIcons]]
icon = "fa-brands fa-google-scholar"
title = "scholar"
url = "https://scholar.google.com/citations?user=fDdLat4AAAAJ"

[[socialIcons]]
icon = "fa-brands fa-instagram"
title = "instagram"
url = "https://instagram.com/thekinsley_gallery/"

[[socialIcons]]
icon = "fa-solid fa-envelope"
title = "e-mail"
url = "kslh99@stu.pku.edu.cn"

[mermaid]
# enable = true