baseURL = 'https://thekinsley.github.io/'
languageCode = 'zh-cn'
title = "theKinsley's 451s"
theme = 'paper'

#disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'theKinsley'                 # github.com/YOUR_GITHUB_ID
  instagram = 'krst_hsu'           # instagram.com/YOUR_INSTAGRAM_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  # rss = true                                # show rss icon

  # home page profile
  avatar = 'https://thumbs2.imgbox.com/77/18/ujp0CvfP_t.jpeg'                 # gravatar email or image url
  name = 'Kinsley Hsu'
  bio = 'Burning my life for CV & NLP in WICT @ Peking Univ.'


  # misc
  # disableHLJS = true                        # disable highlight.js
   monoDarkIcon = true                       # show monochrome dark mode icon
  # gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[menu.main]]
name = "About"
weight = 1
url = "/about/"
[[menu.main]]
name = "Ship"
weight = 3
url = "/rela/"